/'*********************************************************************
Created by : UML Diagram Generator 1.2024.11.4 for XrmToolBox
Tool Author: Jonas Rapp https://jonasr.app/
GitHub     : https://github.com/rappen/LCG-UDG/
Source Org : https://rapptools-dev.crm4.dynamics.com/
Filename   : C:\Dev\GitHub\Tools\Model\Rapp Tools.plantuml
Created    : 2024-12-05 21:08:03
*********************************************************************'/

@startuml Rapp Tools

skinparam RoundCorner 5
skinparam ArrowFontSize 12
skinparam ClassBorderColor Black
skinparam ClassBorderColor<<custom>> Blue
skinparam Padding 1
skinparam linetype ortho
hide circle
hide stereotype

title Rapp Tools Entity Model

footer Generated %date("yyyy-MM-dd") by UML Diagram Generator 1.2024.11.4 for XrmToolBox

entity Account
{
    *Account (PK): Uniqueidentifier
    --
    *AccountName (PN): String
}

entity Contact
{
    *Contact (PK): Uniqueidentifier
    --
    FullName (PN): String
    *LastName: String
}

entity Installation
{
    *Installation (PK): Uniqueidentifier
    --
    *InstallationId (PN): String
}

entity Support
{
    *Support (PK): Uniqueidentifier
    --
    Name (PN): String
    *Customer: Customer
    Amount: Money
    CreatedOn: DateTime
    Installation: Lookup
    Tool: Lookup
}

entity Tool
{
    *Tool (PK): Uniqueidentifier
    --
    *Name (PN): String
    *Shortname: String
}

Contact --{ Account
Account ||--{ Support
Account --{ Contact
Contact ||--{ Support
Contact --{ Support
Installation --{ Support
Tool --{ Support

@enduml


/'**** LCG-configuration-BEGIN ****
<?xml version="1.0" encoding="utf-16"?>
<Settings xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
  <TemplateFormat>PlantUML</TemplateFormat>
  <Version>1.2024.11.4</Version>
  <NameSpace>Rapp Tools</NameSpace>
  <Theme />
  <ColorByType>false</ColorByType>
  <UseCommonFile>true</UseCommonFile>
  <SaveConfigurationInCommonFile>true</SaveConfigurationInCommonFile>
  <FileName>DisplayName</FileName>
  <ConstantName>DisplayName</ConstantName>
  <ConstantCamelCased>false</ConstantCamelCased>
  <DoStripPrefix>false</DoStripPrefix>
  <StripPrefix>_</StripPrefix>
  <XmlProperties>false</XmlProperties>
  <XmlDescription>false</XmlDescription>
  <TypeDetails>false</TypeDetails>
  <Regions>false</Regions>
  <RelationShips>true</RelationShips>
  <RelationshipLabels>false</RelationshipLabels>
  <OptionSets>false</OptionSets>
  <GlobalOptionSets>false</GlobalOptionSets>
  <Legend>false</Legend>
  <TableSize>1</TableSize>
  <RelationShipSize>2</RelationShipSize>
  <CommonAttributes>None</CommonAttributes>
  <AttributeSortMode>AlphabeticalAndRequired</AttributeSortMode>
  <Groups />
  <SelectedEntities>
    <SelectedEntity>
      <Name>account</Name>
      <Attributes>
        <string>accountid</string>
        <string>name</string>
      </Attributes>
      <Relationships>
        <string>account_primary_contact</string>
        <string>rappsol_account_rappsol_support</string>
        <string>contact_customer_accounts</string>
      </Relationships>
    </SelectedEntity>
    <SelectedEntity>
      <Name>contact</Name>
      <Attributes>
        <string>contactid</string>
        <string>fullname</string>
        <string>lastname</string>
      </Attributes>
      <Relationships>
        <string>contact_customer_accounts</string>
        <string>account_primary_contact</string>
        <string>rappsol_contact_rappsol_support</string>
        <string>rappsol_Support_AccountContact_Contact</string>
      </Relationships>
    </SelectedEntity>
    <SelectedEntity>
      <Name>rappsol_installation</Name>
      <Attributes>
        <string>rappsol_installationid</string>
        <string>rappsol_name</string>
      </Attributes>
      <Relationships>
        <string>rappsol_Support_rappsol_Installation</string>
      </Relationships>
    </SelectedEntity>
    <SelectedEntity>
      <Name>rappsol_support</Name>
      <Attributes>
        <string>rappsol_amount</string>
        <string>createdon</string>
        <string>rappsol_customer</string>
        <string>rappsol_installation</string>
        <string>rappsol_name</string>
        <string>rappsol_supportid</string>
        <string>rappsol_tool</string>
      </Attributes>
      <Relationships>
        <string>rappsol_Support_AccountContact_Contact</string>
        <string>rappsol_account_rappsol_support</string>
        <string>rappsol_contact_rappsol_support</string>
        <string>rappsol_Support_rappsol_Tool</string>
        <string>rappsol_Support_rappsol_Installation</string>
      </Relationships>
    </SelectedEntity>
    <SelectedEntity>
      <Name>rappsol_tool</Name>
      <Attributes>
        <string>rappsol_name</string>
        <string>rappsol_shortname</string>
        <string>rappsol_toolid</string>
      </Attributes>
      <Relationships>
        <string>rappsol_Support_rappsol_Tool</string>
      </Relationships>
    </SelectedEntity>
  </SelectedEntities>
</Settings>
**** LCG-configuration-END   ****'/
